### PR TITLE
README.md: replace kvm with qemu in the app-elfloader name

### PR DESCRIPTION
**Pull request by RaduNichita**
Replace the names of the files the README file to match the actual files.

### CODE REVIEW

**Review by StefanJum — APPROVED** [review]
Thanks @RaduNichita 
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Review by razvand — COMMENTED** [review]
Rephrase the commit message to:

```
 README.md: Replace "kvm" with qemu in the image name 
 ```
 
Also add a description of why this is required:
a) because files have been updated in previous commit and the `README.md` is inconsistent
b) because [updates to the build system](https://github.com/unikraft/unikraft/pull/760/commits/8bb46160738b6c14ad167a302ed0658cd9941def) changed `kvm` to `qemu` to allow for multiple VMMs running with KVM (such as Firecraker)

**Review by razvand — COMMENTED** [review]
What I recommend as a full commit message:

```
README.md: Replace "kvm" with "qemu" in the image name

Name update is required for consistency with the image names updated by commit https://github.com/unikraft/run-app-elfloader/commit/cc1538a78b5ff65bc8bc4eb4e0d1e0bacb04d2b5.

This is required since release 0.13, that included an update to image names due to the inclusion of multiple VMMs running with KVM (such as Firecraker), in commit https://github.com/unikraft/unikraft/pull/760/commits/8bb46160738b6c14ad167a302ed0658cd9941def.
```

Of course, make the commit description wrap to 72-80 lines.

**Review by razvand — APPROVED** [review]
Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

**Pull request merged**
